#!/bin/bash
if [[ $# < 1 ]]; then
    echo "Syntax: $0 node.lnx [dbgmode] [execname] [args]"
    exit
fi
xterm -title NODE$1 -geometry 65x25 -bg black -fg white -e "./runNode $*; echo Closing window in 3 seconds...; sleep 3" &
