#!/usr/bin/python

import sys
if len(sys.argv) <= 1:
    print("Syntax: %s file.lnx [dbgmodes] [execname] [args]" % sys.argv[0])
    sys.exit(0)

import os
nodename = "node"
if len(sys.argv) >= 4:
    nodename = sys.argv[3]
if not os.path.exists(nodename):
    print "Error: '%s' executable does not exist. 'make' first?" % nodename
    sys.exit(0)

if not os.path.exists(sys.argv[1]):
    print" Error: file %s does not exist" % sys.argv[0]
    sys.exit(0)

dbgmodes = "all"
if len(sys.argv) >= 3:
    dbgmodes = sys.argv[2]

f = open(sys.argv[1])

mname = f.readline().split(":")[0]
if mname == "localhost":
    cmd = "DBG_MODES=%s \"./%s\" %s %s" % (
        dbgmodes, nodename, sys.argv[1], " ".join(sys.argv[4:]))
else:    
    runfiledir = os.getcwd()
    cmd = "ssh %s DBG_MODES=%s %s %s" % (
        mname, dbgmodes,
        os.path.join(runfiledir, nodename),
        os.path.join(runfiledir, sys.argv[1]))

print cmd
os.system(cmd)
