#!/bin/bash
if [ $# -eq 4 ]; then
   ip link set $1 up
   ip link set $1 mtu 250
   ip addr add $3 peer $4 dev $1
   ifconfig $1
else
   echo "usage: tunup <devicename> <user> <clientip> <serverip>"
fi
