#!/usr/bin/python

import sys
if len(sys.argv) <= 1:
    print("Syntax: %s file.lnx [dbgmodes]" % sys.argv[0])
    sys.exit(0)

import os
if not os.path.exists("node"):
    print "Error: 'node' executable does not exist. 'make' first?"
    sys.exit(0)

if not os.path.exists(sys.argv[1]):
    print" Error: file %s does not exist" % sys.argv[0]
    sys.exit(0)

dbgmodes = "all"
if len(sys.argv) >= 3:
    dbgmodes = sys.argv[2]

f = open(sys.argv[1])

mname = f.readline().split(":")[0]
if mname == "localhost":
    cmd = "DBG_MODES=%s ./node %s" % (dbgmodes, sys.argv[1])
else:    
    runfiledir = os.getcwd()
    cmd = "ssh %s DBG_MODES=%s %s %s" % (
        mname, dbgmodes,
        os.path.join(runfiledir, "node"),
        os.path.join(runfiledir, sys.argv[1]))

print cmd
os.system(cmd)
