#!/bin/bash -e

CONFIG=Config.sh
if [[ ! -e $CONFIG ]] ; then
	cp $CONFIG.default $CONFIG
fi

redo-ifchange $CONFIG

./conf-check $CONFIG $CONFIG.default >&2
if [[ 0 -ne $? ]]; then
	exit 1
fi

source $CONFIG

echo "# DO NOT EDIT THIS FILE" >>$3
echo "# This file is generated from $CONFIG. Edit that file instead." >>$3

echo "COMPILE_CONFIG_BOOLS=\"$COMPILE_CONFIG_BOOLS\"" >>$3
echo "COMPILE_CONFIG_DEFS=\"$COMPILE_CONFIG_DEFS\"" >>$3

for var in $COMPILE_CONFIG_BOOLS $COMPILE_CONFIG_DEFS ; do
	echo "$var=$(eval echo \$$var)" >>$3
done

redo-stamp <$3
