#!/usr/bin/python

import sys
if len(sys.argv) <= 1:
    print("Usage: %s network.net [dbgmodes]" % sys.argv[0])
    sys.exit()

import os
if not os.path.exists(sys.argv[1]):
    print "Error: file %s does not exist" % sys.argv[1]
    sys.exit()

#import time, random
for l in open(sys.argv[1]):
    s = l.split()
    if len(s) != 3: continue
    if s[0] == "node":
        cmd = "./runNodeWin %s.lnx %s" % (s[1], " ".join(sys.argv[2:]))
        print cmd
        os.system(cmd)
